<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'users' => [[], ['_controller' => 'App\\Controller\\UserController::usersAll'], [], [['text', '/users']], [], []],
    'users_galleries' => [['id'], ['_controller' => 'App\\Controller\\UserController::usersAllGalleries'], ['id' => '\\d+'], [['text', '/galleries'], ['variable', '/', '\\d+', 'id', true], ['text', '/users']], [], []],
];
